### ISSUE TITLE
Add some guidance on running the script on a Windows environment

### ISSUE THREAD

**Issue by pmqs** [pmqs/Fix-OneDrive-Zip#1]
There have been a couple of Windows users who have had difficulty in running the script.

Can use this reply below as the starting point for some new documentation

This tool is run from a Windows terminal shell, like cmd or PowerShell.

Start by downloading the code from GitHub onto your Windows box. You only need to download the file "fix-onedrive-zip"

To run my code on Windows you first need to check if you have Perl installed. For Linux systems this isn't an issue, because they all ship with one. On Windows you need to install one, if you don't already have it.
To find out, run up cmd  (type Windows-R, the type cmd). You should now be a terminal window. Type "perl -v"

On my setup it prints this 

    C:\Users\xx>perl -v

    This is perl 5, version 30, subversion 1 (v5.30.1) built for MSWin32-x64-multi-thread

    Copyright 1987-2019, Larry Wall

    Perl may be copied only under the terms of either the Artistic License or the
    GNU General Public License, which may be found in the Perl 5 source kit.

    Complete documentation for Perl, including FAQ lists, should be found on
    this system using "man perl" or "perldoc perl".  If you have access to the
    Internet, point your browser at http://www.perl.org/, the Perl Home Page.

If you don't get that, install one of the Windows Perl distributions. http://strawberryperl.com/ is a good choice. Pick the 64-bit option & install. (http://strawberryperl.com/download/5.32.0.1/strawberry-perl-5.32.0.1-64bit.msi)

Finally, to fix your file, copy my script to the same directory as your zip file, then open a cmd terminal in that directory and run -- 

    perl fix-onedrive-zip yourfile.zip

**Comment by megmasson** [comment]
Hi Paul, I'm a perl novice but I've been searching for a means to open large zip files. I've followed all the steps outlinedabove for a windows user. However I keep getting the following error: Can't open perl script "fix-onedrive-zip-new": No such file or directory

Any pointers would be greatly appreciated. 

Thanks,
Megan

**Comment by pmqs** [comment]
Hey Megan,

I assume you are running Windows and you have perl installed?

If that is the case then the most straightforward way to run the script is to make sure that both the `fix-onedrive-zip` script and the zip file you want to fix are in the same directory.

If that is the case, then open a command window and run

`perl fix-onedrive-zip yourfile.zip
`

If that doesn't work, can you get me a log (or screenshots) of what you tried please?

**Comment by megmasson** [comment]
Hi Paul,

 

Thanks for getting back to me. Please see the screen shot below and the script attached that is saved in the same directory as my zipped file.

 

Thanks,

 

Megan

 



 

 

Megan Masson (BSc (Hons) Geology, Pr. Sci Nat 400186/15)
Groundwater Modeller

C: 082 808 4730 |

**Comment by megmasson** [comment]
Hi Paul, 
Please see the screen print below. Thanks for the help. 

![Screenprint](https://user-images.githubusercontent.com/92025151/136212985-ba69e0ec-79fb-444c-9943-436c683d4188.png)
