### ISSUE TITLE
Error: No such file or directory

### ISSUE THREAD

**Issue by shivaldube** [pmqs/Fix-OneDrive-Zip#10]
Hi Paul, I've followed all the steps outlined above for a windows user. However I keep getting the following error: Can't open perl script "fix-onedrive-zip-new": No such file or directory

Any pointers would be greatly appreciated.

Thanks,
![fix-onedrive-zip error](https://github.com/pmqs/Fix-OneDrive-Zip/assets/98322402/a49e81e6-ace1-46f1-a5db-d8f5f96e0dd4)

**Comment by pmqs** [comment]
Hey @shivaldube 

that's a very strange error. The wording suggests that you do have `perl` installed, but for some reason it cannot execute the `fix-onedrive-zip` script.

When you run `ls fix-onedrive-zip` does it complain?

Try running like this

```
perl .\fix-onedrive-zip` myfile.zip
```

**Comment by shivaldube** [comment]
Hi Paul,
Here is the screenshot when I try running ls fix-onedrive-zip

![Error ls](https://github.com/pmqs/Fix-OneDrive-Zip/assets/98322402/5eaa1cb2-bf4d-440e-9017-bf20316118fb)

**Comment by pmqs** [comment]
The fact that your initial screenshot showed a directory that did have `fix-onedrive-zip` present, but the `ls` command does not see it suggests the filename may contains some unexpected characters.

Does running `ls` (without any parameters) output the  `fix-onedrive-zip` script name?

Try renaming  `fix-onedrive-zip` to `myscript` and run `perl myscript myfile`

**Comment by shivaldube** [comment]
Hi Paul,
Thanks for the help. Still no luck.

![Error](https://github.com/pmqs/Fix-OneDrive-Zip/assets/98322402/7e67f9e9-1447-4c12-ace8-80f8b99669c0)

**Comment by shivaldube** [comment]
Hi Paul,
Thanks a lot for the replies and help the script worked. I have to write the file name with extension like myscript.txt

![worked!!](https://github.com/pmqs/Fix-OneDrive-Zip/assets/98322402/a5391dd9-0c64-4a0f-a51b-494f207be776)

Thanks again!!

**Comment by pmqs** [comment]
Excellent!
