### ISSUE TITLE
Getting unable to read file error when running script

### ISSUE THREAD

**Issue by DeirdreRodgers** [pmqs/Fix-OneDrive-Zip#13]
```
Fix-OneDrive-Zip-master  $ ./fix-onedrive-zip Pantelis.zip

Checking 'Pantelis.zip'
Cannot read from 'Pantelis.zip':

```

**Comment by DeirdreRodgers** [comment]
I'm on mac.. I assumed I had the issue this script was created to solve but maybe not

**Comment by DeirdreRodgers** [comment]
Its failing here for me, can you tell me what it means?

`sub Read
{
    my $filename = shift ;
    my $fh = shift;
    my $size = shift ;

    my $data ;

    read($fh, $data, $size) == $size
        or die "Cannot read from '$filename': $!\n" ;

    return $data;`

**Comment by pmqs** [comment]
My code has been able to open the file, but it is failing when reading data from it. That failure suggests that your zip file `Pantelis.zip` is probably truncated.
Can you determine the size of the file please? Run these please

```
ls -l Pantelis.zip

ls -lh Pantelis.zip
```

**Comment by DeirdreRodgers** [comment]
lol its 0 bytes, must have been an issue with the download even though it took about 5 mins to download. thanks for reply and sorry I should have check that out

**Comment by pmqs** [comment]
No worries
