### ISSUE TITLE
Error: Cannot find Zip signature at end of *.zip

### ISSUE THREAD

**Issue by ahinoamp** [pmqs/Fix-OneDrive-Zip#2]
Hi,

I just found this script and was hoping it would work for a zip file I downloaded from OneDrive but I got the above mentioned error.

The original error I got while trying to unzip using 7zip was: "unexpected end of data" or "the compresses zipped folder is invalid" from the Windows utility.

Do you have any thoughts? 

Thanks,

Noe

**Comment by pmqs** [comment]
If my code is outputting that message it means that

1. It had found the correct data at the start of the Zip file (which is good).

1. but it is missing a vital part of the zip file at the end of the file.

Is there any chance that the download was terminated early? This error suggests that the file has been truncated.

If you want to dig deeper, get a copy of [zipdetails](https://github.com/pmqs/IO-Compress/blob/master/bin/zipdetails). Run the following and post the output

`zipdetails yourfile.zip`

If that complains about not finding signatures, run this and post the output

`zipdetails --scan yourfile.zip`

**Comment by pmqs** [comment]
No updates in over a month.

Closing issue
