### ISSUE TITLE
Guidance for Linux Install

### ISSUE THREAD

**Issue by Nightshade4317** [pmqs/Fix-OneDrive-Zip#3]
I am relatively new at ubuntu and i have done everything i know.

- chmod +x /home/nandan/Downloads/Fix-OneDrive-Zip-master/fix-onedrive-zip
- installing perl, mysql

And still i cant seem to get how to run the script.....

Any advice is much appreciated

**Comment by pmqs** [comment]
> I am relatively new at ubuntu and i have done everything i know.
> 
> * chmod +x /home/nandan/Downloads/Fix-OneDrive-Zip-master/fix-onedrive-zip
> * installing perl, mysql
> 
> And still i cant seem to get how to run the script.....
> 
> Any advice is much appreciated

The script should run on any platform that has a Perl binary installed (my test harness on GitHub tests it on Linux, Windows & MacOS). Ubuntu comes preinstalled with `perl`, so you shouldn't have to install it. `mysql` isn't needed for this script.

Something like this should be enough to run the script, assuming you have copied the script to `/home/nandan/Downloads/Fix-OneDrive-Zip-master/fix-onedrive-zip`

```
$ perl /home/nandan/Downloads/Fix-OneDrive-Zip-master/fix-onedrive-zip yourfile.zip
```

or this

```
$ chmod a+x /home/nandan/Downloads/Fix-OneDrive-Zip-master/fix-onedrive-zip
$ /home/nandan/Downloads/Fix-OneDrive-Zip-master/fix-onedrive-zip yourfile.zip
```

If that doesn't work can you post the complete output you get when try to run the script -- I need to see any the error messages that are output.

**Comment by Nightshade4317** [comment]
![Screenshot from 2021-05-16 22-36-28](https://user-images.githubusercontent.com/84279634/118405841-4cd0c780-b697-11eb-971a-02927872ad53.png)


This is what i get...

**Comment by pmqs** [comment]
> ![Screenshot from 2021-05-16 22-36-28](https://user-images.githubusercontent.com/84279634/118405841-4cd0c780-b697-11eb-971a-02927872ad53.png)
> 
> This is what i get...

The error you are getting is saying that my script cannot find the zip file you want fixed.

What is the _exact_ name of the zip file you want to fix and what directory is it in?  You have tried running with both `Unzip.zip` and `unzip.zip`. In Linux that maps to two different files -- filenames in Linux are case sensitive.


Is the zip file you want to fix in the current directory?  The way you are running the script assumes that it is.


Try running the script with the absolute path to the zip file. Assuming your zip file is `/full/path/to/unzip.zip`, run this

```
$ perl home/nandan/Downloads/Fix-OneDrive-Zip-master/fix-onedrive-zip /full/path/to/unzip.zip
```

Alternatively, `cd` into the directory where the zip file is stored an run the script like this

```
$ cd /directory/with/the/zip/file
$ ls -l
$ perl home/nandan/Downloads/Fix-OneDrive-Zip-master/fix-onedrive-zip unzip.zip
```

**Comment by Nightshade4317** [comment]
![Screenshot from 2021-05-16 22-52-50](https://user-images.githubusercontent.com/84279634/118406383-7b4fa200-b699-11eb-9d95-8cc9c87553e0.png)
All of this is in the downloads folder

**Comment by Nightshade4317** [comment]
Fyi fix-onedrive-zip-master is the extracted file from here
![Screenshot from 2021-05-16 22-48-53](https://user-images.githubusercontent.com/84279634/118406268-f1073e00-b698-11eb-9ed8-4aeea2475bd5.png)
I also tried 
`fix-onedrive-zip` [--dry-run] Recordings.zip`
after verifying i had perl and that i had run the script using
`perl fix-onedrive-zip`

Also sorry if i missed something.... This is my 5th day on linux

**Comment by pmqs** [comment]
The `Downloads` folder is usually a sub-directory off you home directory, so  try this

```
$ perl ~/Downloads/Fix-OneDrive-Zip-master/fix-onedrive-zip ~/Downloads/Unzip.zip
$ unzip -t /Downloads/Unzip.zip
```

**Comment by Nightshade4317** [comment]
![Screenshot from 2021-05-16 23-01-33](https://user-images.githubusercontent.com/84279634/118406722-b1415600-b69a-11eb-96a4-62b0b0a31bac.png)

**Comment by pmqs** [comment]
sorry - missed a `~` -- the `unzip` command should look like this

```
$ unzip -t ~/Downloads/Unzip.zip
```

**Comment by Nightshade4317** [comment]
Yeah i think that worked.
Thank you so much for your help...
Regards,
Nandan

![Screenshot from 2021-05-16 23-06-12](https://user-images.githubusercontent.com/84279634/118406846-6247f080-b69b-11eb-8796-c9b7efde5a87.png)

**Comment by pmqs** [comment]
Good. We got there in the end.
