### ISSUE TITLE
Hi, just one more question...

### ISSUE THREAD

**Issue by Nightshade4317** [pmqs/Fix-OneDrive-Zip#4]
Good. We got there in the end.

_Originally posted by @pmqs in https://github.com/pmqs/Fix-OneDrive-Zip/issues/3#issuecomment-841849900_

Is there an output for that last command?
I didnt find a new folder there and i couldnt unzip it from files either... so what do i do next to access my files?

**Comment by Nightshade4317** [comment]
Even though the script worked, i am still not able to unzip the file
![Screenshot from 2021-05-16 23-18-38](https://user-images.githubusercontent.com/84279634/118407165-14cc8300-b69d-11eb-935c-6cfea2a9bdb9.png)
![Screenshot from 2021-05-16 23-19-12](https://user-images.githubusercontent.com/84279634/118407191-2d3c9d80-b69d-11eb-9925-8ee577ce59a4.png)

**Comment by pmqs** [comment]
Didn't notice that the output from the `unzip -t` command shows there is still an issue with  your zip file. 

![image](https://user-images.githubusercontent.com/2691108/118407383-6f9fb380-b678-11eb-9b2b-b0ba402e44d3.png)

Looks like there is another issue with your zip file. Not clear what that is.

Try running this to see what you can extract from `Unzip.zip`

```
$ cd ~/Downloads
$ unzip Unzip.zip
```

that should hopefully create two sub-directories called `Recordings` and `__Recordings`. 

That will extract some (or possibly all) of the files from `Unzip.zip`. Can you check if all the files you expect are extracted?

**Comment by Nightshade4317** [comment]
I ran the above commands...
Result:
`Archive:  Unzip.zip
error: End-of-centdir-64 signature not where expected (prepended bytes?)
  (attempting to process anyway)
warning [Unzip.zip]:  42188800 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  42188800
  (attempting to re-compensate)
 extracting: Recordings/10 G1 Mathematics _20210511_084535.mp4  
 extracting: Recordings/10G1 Computer Applications-20210503_131718-Meeting Recording.mp4  
 extracting: Recordings/10G1 Icse Biology Practical-20210508_103030-Meeting Recording.mp4  
 extracting: Recordings/10G1 Icse Biology-20210504_095951-Meeting Recording.mp4  
 extracting: Recordings/10G1 Icse Biology-20210505_141539-Meeting Recording.mp4  
 extracting: Recordings/10G1 Icse Biology-20210507_110045-Meeting Recording.mp4  
 extracting: Recordings/10G1 Icse Biology-20210512_141458-Meeting Recording.mp4  
 extracting: Recordings/10G1 icse chemistry [new batch 2021-22]-20210427_120018-Meeting Recording.mp4  
 extracting: Recordings/10G1 Icse Chemistry-20210504_115840-Meeting Recording.mp4  
 extracting: Recordings/10G1 Icse Chemistry-20210505_151606-Meeting Recording.mp4  
 extracting: Recordings/10G1 Icse Chemistry-20210512_151525-Meeting Recording.mp4  
 extracting: Recordings/10G1 new  A1,A2,A4 2021-22  Biology-20210427_095709-Meeting Recording.mp4  
 extracting: Recordings/10th ICSE G1 Computer Applications-20210430_120848-Meeting Recording.mp4  
 extracting: Recordings/10th ICSE G1 Computer Applications-20210507_120254-Meeting Recording.mp4  
 extracting: Recordings/10th ICSE G1 Computer Applications-20210510_132238-Meeting Recording.mp4  
 extracting: Recordings/Meeting in 'New 10th G1(A1,A2,A4)-2021-22'_20210510_042836.mp4  
 extracting: Recordings/Meeting in 'New 10th G1(A1,A2,A4)-2021-22'_20210512_052744.mp4  
 extracting: Recordings/Meeting now-20210430_110810-Meeting Recording.mp4  
 extracting: Recordings/Meeting now-20210503_141454-Meeting Recording.mp4  
 extracting: Recordings/Meeting now-20210507_095856-Meeting Recording.mp4  
 extracting: Recordings/Meeting now-20210510_141437-Meeting Recording.mp4  
 extracting: Recordings/Meeting now-20210510_151541-Meeting Recording.mp4  
 extracting: Recordings/Meeting now-20210511_100018-Meeting Recording.mp4  
 extracting: Recordings/Meeting now-20210511_115906-Meeting Recording.mp4  
 extracting: Recordings/Meeting now-20210512_115924-Meeting Recording.mp4  
 extracting: Recordings/Meeting-20210506_141403-Meeting Recording.mp4  
 extracting: Recordings/Meeting-20210511_105843-Meeting Recording.mp4  
 extracting: Recordings/NEW 10 G1 CIVICS-20210430_095932-Meeting Recording.mp4  
 extracting: Recordings/New 10 G1 ICSE CIVICS _20210505_062802.mp4  
 extracting: Recordings/NEW 10 G1 ICSE CIVICS_20210428_063136.mp4  
 extracting: Recordings/NEW 10 G1 ICSE CIVICS-20210511_131708-Meeting Recording.mp4  
 extracting: Recordings/New 10G1 Icse Biology-20210428_141435-Meeting Recording.mp4  
 extracting: Recordings/New 10G1 Icse Chemistry-20210428_151931-Meeting Recording.mp4  
file #34:  bad zipfile offset (local header sig):  9215558655
  (attempting to re-compensate)
 extracting: __Recordings/New 10G1 icse chemistry-20210503_151640-Meeting Recording.mp4_Error.txt  
 extracting: __Recordings/New 10G1 ICSE CIVICS-20210427_134603-Meeting Recording.mp4_Error.txt  
 extracting: __Recordings/NEW 10TH ICSE GROUP 1 ENGLISH-20210504_112054-Meeting Recording.mp4_Error.txt  
 extracting: __Recordings/NEW 10TH ICSE GROUP 1 ENGLISH-20210505_110710-Meeting Recording.mp4_Error.txt  
 extracting: __Recordings/New 10th ICSE Group1 English-20210428_105949-Meeting Recording.mp4_Error.txt  
 extracting: __Recordings/orientation programme new 10th G1 icse A1 A2 A4 2021-22-20210426_133059-Meeting Recording.mp4_Error.txt  
 extracting: ___All_Errors.txt`
There were 39 items in the folder.
33 items were successfully unzipped.
But its ok.. i can re-download them.
Thanks
