### ISSUE TITLE
Cannot find zip signature at the end of the file!

### ISSUE THREAD

**Issue by Ankit89Git** [pmqs/Fix-OneDrive-Zip#7]

**Comment by pmqs** [comment]
If my code is outputting that message it means that

1. It had found the correct data at the start of the Zip file (which is good).

1. but it is missing a vital part of the zip file at the end of the file.

Is there any chance that the download was terminated early? This error suggests that the file has been truncated.

If you want to dig deeper, get a copy of [zipdetails](https://github.com/pmqs/IO-Compress/blob/master/bin/zipdetails). Run the following and post the output

```
zipdetails yourfile.zip
```

If that complains about not finding signatures, run this and post the output

```
zipdetails --scan yourfile.zip
```

Also, if you have access to `unzip`, run `unzip -t yourfile.zip`. That will test the zip file.

Alternatively, can you give me access to the zip file?

**Comment by Ankit89Git** [comment]
Hi Paul,

Thank you for your swift response.

Please find the output below inline.

Due to data privacy issues, I won’t be able to share access to the ZIP file. I am downloading files from OneDrive.

Best regards,
Ankit

**Comment by pmqs** [comment]
> Hi Paul, Thank you for your swift response. Please find the output below inline. Due to data privacy issues, I won’t be able to share access to the ZIP file. I am downloading files from OneDrive. 
>Best regards, Ankit 

Hey Ankit

you have just posted a copy of the `zipdetails` script itself -- I need the output you get when you run it. Also - I noticed that I pointed you to an old copy of the script -- use this version instead [zipdetails](https://github.com/pmqs/zipdetails/blob/main/bin/zipdetails)

**Comment by Ankit89Git** [comment]
Hi Paul,

How do I save the file as an executable file? It’s currently text file.

Best regards,
Ankit

**Comment by Ankit89Git** [comment]
Paul,

I am getting this error message.

Best regards,
Ankit

**Comment by pmqs** [comment]
>How do I save the file as an executable file? It’s currently text file

The program is a `perl` script -- it is supposed to be text. You just save it into a file called `zipdetails`

To run the script you need to have `perl` available. Not sure what platform you are running, but perl is widely available.

Assuming you have `perl` installed, run this from a terminal window

```
perl zipdetails yourfile.zip
```
If that complains, try with the `walk` option

```
perl zipdetails --walk yourfile.zip
```

**Comment by pmqs** [comment]
Explain reason for error in dd94a63249744e6fc17b28e5a14f8848d21a8709

**Comment by Ankit89Git** [comment]
Thanks, Paul for sharing the details.

So, it seems there is no option but to download again. Microsoft should do something about all these large files getting corrupted while downloading from OneDrive.


Best regards,
Ankit

**Comment by pmqs** [comment]
@Ankit89Git there is one possibility I hadn't thought of.

If you get a chance, could you save the code below in "try.pl" and run it with your perl executable please

```
# Check for a 32-bit Perl
if (!eval { pack "Q", 1 }) {
    print "fix-onedrive-zip requires 64 bit integers, ",
            "this Perl has 32 bit integers.\n";
}

print "all is ok\n";
```

this is what I get

```
$ perl try.pl
all is ok
```
If you don't get th eoutput `all is ok`, please get back to me.
